/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/documents/{documentUuid}/metadata': {
    /**
     * Replace the metadata associated with a document
     * @description Accepts JSON based metadata to associate with the document identified by the supplied unique identifier. Applies authorisation and validation rules based on the type of document. If valid, the previous metadata will be stored and the metadata associated with the document will be replaced with the supplied metadata.
     *
     * Requires one of the following roles:
     * * DOCUMENT_WRITER
     * * DOCUMENT_ADMIN
     */
    put: operations['replaceDocumentMetadata']
  }
  '/documents/{documentType}/{documentUuid}': {
    /**
     * Upload a document file and associated metadata and store against a unique identifier
     * @description Accepts a document file binary and associated metadata. Uses the supplied document type to apply any validation rules and extra security then stores the file, creates and populates a document object with file properties and supplied metadata and saves that document object. The document is associated with the client supplied unique identifier. This identifier is used as an idempotency key and therefore cannot be reused once the upload operation is successful.
     *
     * Requires one of the following roles:
     * * DOCUMENT_WRITER
     * * DOCUMENT_ADMIN
     */
    post: operations['uploadDocument']
  }
  '/documents/search': {
    /**
     * Search for documents with matching metadata and optionally document type
     * @description Uses the supplied metadata and optional document type to filter and return documents. Documents will match if they are of the supplied type (optional) and/or their metadata contains all the supplied properties and their values e.g. prisonCode = "KMI" AND prisonNumber = "A1234BC". Value matching is partial and case insensitive so court = "ham magis" will match "Birmingham Magistrates".
     *
     * Requires one of the following roles:
     * * DOCUMENT_READER
     * * DOCUMENT_ADMIN
     */
    post: operations['searchDocuments']
  }
  '/documents/{documentUuid}': {
    /**
     * Get a document by its unique identifier
     * @description Returns document properties and metadata associated with the document. The document file must be downloaded separately using the GET /documents/{documentUuid}/file endpoint.
     *
     * Requires one of the following roles:
     * * DOCUMENT_READER
     * * DOCUMENT_ADMIN
     */
    get: operations['getDocument']
    /**
     * Delete a document by its unique identifier
     * @description
     *
     * Requires one of the following roles:
     * * DOCUMENT_WRITER
     * * DOCUMENT_ADMIN
     */
    delete: operations['deleteDocument']
  }
  '/documents/{documentUuid}/file': {
    /**
     * Download a document file by its unique identifier
     * @description Returns document file binary with Content-Type and Content-Disposition headers.
     *
     * Requires one of the following roles:
     * * DOCUMENT_READER
     * * DOCUMENT_ADMIN
     */
    get: operations['downloadDocumentFile']
  }
}

export type webhooks = Record<string, unknown>

export interface components {
  schemas: {
    /**
     * @description JSON structured metadata associated with the document. May contain prison codes, prison numbers, dates, tags etc. and the properties available will be defined by the document's type.
     * @example {
     *   "prisonCode": "KMI",
     *   "prisonNumber": "C3456DE",
     *   "court": "Birmingham Magistrates",
     *   "warrantDate": "2023-11-14"
     * }
     */
    JsonNode: Record<string, unknown>
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Document properties and metadata associated with the document. The document file must be downloaded separately using the GET /documents/{documentUuid}/file endpoint. */
    Document: {
      /**
       * Format: uuid
       * @description The unique identifier assigned to the document
       * @example 8cdadcf3-b003-4116-9956-c99bd8df6a00
       */
      documentUuid: string
      /**
       * @description The type or category of the document within HMPPS
       * @example HMCTS_WARRANT
       * @enum {string}
       */
      documentType: 'HMCTS_WARRANT' | 'SUBJECT_ACCESS_REQUEST_REPORT'
      /**
       * @description The filename of the document file when it was uploaded with the file extension removed
       * @example warrant_for_remand
       */
      filename: string
      /**
       * @description The file extension of the document file
       * @example pdf
       */
      fileExtension: string
      /**
       * Format: int64
       * @description The file size in bytes of the document file
       * @example 48243
       */
      fileSize: number
      /**
       * @description The md5 hash of the document file
       * @example d58e3582afa99040e27b92b13c8f2280
       */
      fileHash: string
      /**
       * @description The application/pdf of the document file
       * @example pdf
       */
      mimeType: string
      metadata: components['schemas']['JsonNode']
      /**
       * Format: date-time
       * @description The date and time this document was uploaded and created in the service
       */
      createdTime: string
      /**
       * @description The name of the service that was used to upload the document file
       * @example Remand and Sentencing
       */
      createdByServiceName: string
      /**
       * @description The username of the user that uploaded the document file
       * @example AAA01U
       */
      createdByUsername?: string
    }
    /** @description Describes the search parameters to use to filter documents. */
    DocumentSearchRequest: {
      /**
       * @description The type or category of the document within HMPPS (optional)
       * @example HMCTS_WARRANT
       * @enum {string}
       */
      documentType?: 'HMCTS_WARRANT' | 'SUBJECT_ACCESS_REQUEST_REPORT'
      metadata: components['schemas']['JsonNode']
    }
    /** @description Describes the search parameters that were used to filter documents and the documents matching the supplied search parameters */
    DocumentSearchResult: {
      request: components['schemas']['DocumentSearchRequest']
      /** @description The documents matching the supplied search parameters */
      results: components['schemas']['Document'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /**
   * Replace the metadata associated with a document
   * @description Accepts JSON based metadata to associate with the document identified by the supplied unique identifier. Applies authorisation and validation rules based on the type of document. If valid, the previous metadata will be stored and the metadata associated with the document will be replaced with the supplied metadata.
   *
   * Requires one of the following roles:
   * * DOCUMENT_WRITER
   * * DOCUMENT_ADMIN
   */
  replaceDocumentMetadata: {
    parameters: {
      header: {
        /** @description Client supplied name of the calling service. This should be the product name of the service as listed in the developer portal */
        'Service-Name': string
        /** @description The username of the user interacting with the client service */
        Username?: string
      }
      path: {
        /** @description Document unique identifier */
        documentUuid: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JsonNode']
      }
    }
    responses: {
      /** @description Document metadata replaced successfully */
      202: {
        content: {
          'application/json': components['schemas']['Document']
        }
      }
      /** @description Bad request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role. Note that the required role can be document type dependent */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Upload a document file and associated metadata and store against a unique identifier
   * @description Accepts a document file binary and associated metadata. Uses the supplied document type to apply any validation rules and extra security then stores the file, creates and populates a document object with file properties and supplied metadata and saves that document object. The document is associated with the client supplied unique identifier. This identifier is used as an idempotency key and therefore cannot be reused once the upload operation is successful.
   *
   * Requires one of the following roles:
   * * DOCUMENT_WRITER
   * * DOCUMENT_ADMIN
   */
  uploadDocument: {
    parameters: {
      header: {
        /** @description Client supplied name of the calling service. This should be the product name of the service as listed in the developer portal */
        'Service-Name': string
        /** @description The username of the user interacting with the client service */
        Username?: string
      }
      path: {
        /** @description The type of document being uploaded. This categorises the document and may enforce additional authentication and validation rules */
        documentType: 'HMCTS_WARRANT' | 'SUBJECT_ACCESS_REQUEST_REPORT'
        /** @description Client supplied document unique identifier. A version 1 or version 4 (preferred) UUID. Used as an idempotency key preventing duplicate document uploads */
        documentUuid: string
      }
    }
    requestBody?: {
      content: {
        'application/json': {
          /**
           * Format: binary
           * @description File part of the multipart request
           */
          file: string
          /** @description The metadata describing the uploaded document. Should contain a person identifier e.g. prison number or case reference number along with any other pertinent metadata. The document type used will specify what metadata is required as a minimum */
          metadata: string
        }
      }
    }
    responses: {
      /** @description Document and associated metadata uploaded successfully */
      201: {
        content: {
          'application/json': components['schemas']['Document']
        }
      }
      /** @description Bad request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role. Note that the required role can be document type dependent */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Conflict, the supplied document unique identifier is already present in the service */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Search for documents with matching metadata and optionally document type
   * @description Uses the supplied metadata and optional document type to filter and return documents. Documents will match if they are of the supplied type (optional) and/or their metadata contains all the supplied properties and their values e.g. prisonCode = "KMI" AND prisonNumber = "A1234BC". Value matching is partial and case insensitive so court = "ham magis" will match "Birmingham Magistrates".
   *
   * Requires one of the following roles:
   * * DOCUMENT_READER
   * * DOCUMENT_ADMIN
   */
  searchDocuments: {
    parameters: {
      header: {
        /** @description Client supplied name of the calling service. This should be the product name of the service as listed in the developer portal */
        'Service-Name': string
        /** @description The username of the user interacting with the client service */
        Username?: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentSearchRequest']
      }
    }
    responses: {
      /** @description Search request accepted and results returned */
      202: {
        content: {
          'application/json': components['schemas']['DocumentSearchResult']
        }
      }
      /** @description Bad request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role. Note that the required role can be document type dependent */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Get a document by its unique identifier
   * @description Returns document properties and metadata associated with the document. The document file must be downloaded separately using the GET /documents/{documentUuid}/file endpoint.
   *
   * Requires one of the following roles:
   * * DOCUMENT_READER
   * * DOCUMENT_ADMIN
   */
  getDocument: {
    parameters: {
      header: {
        /** @description Client supplied name of the calling service. This should be the product name of the service as listed in the developer portal */
        'Service-Name': string
        /** @description The username of the user interacting with the client service */
        Username?: string
      }
      path: {
        /** @description Document unique identifier */
        documentUuid: string
      }
    }
    responses: {
      /** @description Document found */
      200: {
        content: {
          'application/json': components['schemas']['Document']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role. Note that the required role can be document type dependent */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The document associated with this unique identifier was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Delete a document by its unique identifier
   * @description
   *
   * Requires one of the following roles:
   * * DOCUMENT_WRITER
   * * DOCUMENT_ADMIN
   */
  deleteDocument: {
    parameters: {
      header: {
        /** @description Client supplied name of the calling service. This should be the product name of the service as listed in the developer portal */
        'Service-Name': string
        /** @description The username of the user interacting with the client service */
        Username?: string
      }
      path: {
        /** @description Document unique identifier */
        documentUuid: string
      }
    }
    responses: {
      /** @description Document deleted */
      202: {
        content: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role. Note that the required role can be document type dependent */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The document associated with this unique identifier was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Download a document file by its unique identifier
   * @description Returns document file binary with Content-Type and Content-Disposition headers.
   *
   * Requires one of the following roles:
   * * DOCUMENT_READER
   * * DOCUMENT_ADMIN
   */
  downloadDocumentFile: {
    parameters: {
      header: {
        /** @description Client supplied name of the calling service. This should be the product name of the service as listed in the developer portal */
        'Service-Name': string
        /** @description The username of the user interacting with the client service */
        Username?: string
      }
      path: {
        /** @description Document unique identifier */
        documentUuid: string
      }
    }
    responses: {
      /** @description Document found */
      200: {
        content: {
          'application/pdf': string
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/pdf': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role. Note that the required role can be document type dependent */
      403: {
        content: {
          'application/pdf': components['schemas']['ErrorResponse']
        }
      }
      /** @description The document associated with this unique identifier was not found. */
      404: {
        content: {
          'application/pdf': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
