/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/queue-admin/retry-dlq/{dlqName}': {
    put: operations['retryDlq']
  }
  '/queue-admin/retry-all-dlqs': {
    put: operations['retryAllDlqs']
  }
  '/queue-admin/purge-queue/{queueName}': {
    put: operations['purgeQueue']
  }
  '/court-maintenance/id/{courtId}': {
    /**
     * Update specified court details
     * @description Updates court information, role required is MAINTAIN_REF_DATA
     */
    put: operations['updateCourt']
  }
  '/court-maintenance/id/{courtId}/buildings/{buildingId}': {
    /**
     * Update specified building details
     * @description Updates building information, role required is MAINTAIN_REF_DATA
     */
    put: operations['updateBuilding']
    /**
     * Delete specified building
     * @description Deletes building information, role required is MAINTAIN_REF_DATA
     */
    delete: operations['deleteBuilding']
  }
  '/court-maintenance/id/{courtId}/buildings/{buildingId}/contacts/{contactId}': {
    /**
     * Update specified building contact details
     * @description Updates contact information, role required is MAINTAIN_REF_DATA
     */
    put: operations['updateContact']
    /**
     * Delete specified building contact details
     * @description Deletes contact information, role required is MAINTAIN_REF_DATA
     */
    delete: operations['deleteContact']
  }
  '/court-maintenance': {
    /**
     * Add a new court
     * @description Adds a new court information, role required is MAINTAIN_REF_DATA
     */
    post: operations['insertCourt']
  }
  '/court-maintenance/id/{courtId}/buildings': {
    /**
     * Add a new building to a court
     * @description Adds a new building to court, role required is MAINTAIN_REF_DATA
     */
    post: operations['insertBuilding']
  }
  '/court-maintenance/id/{courtId}/buildings/{buildingId}/contacts': {
    /**
     * Add a new contact to a building
     * @description Adds a new contact to building, role required is MAINTAIN_REF_DATA
     */
    post: operations['insertContact']
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    get: operations['getDlqMessages']
  }
  '/courts': {
    /**
     * Get all active courts
     * @description All courts (active only)
     */
    get: operations['getActiveCourts']
  }
  '/courts/types': {
    /**
     * Get all types of court
     * @description All court types
     */
    get: operations['getCourtTypes']
  }
  '/courts/paged': {
    /**
     * Get page of courts
     * @description Page of courts
     */
    get: operations['getPageOfCourts']
  }
  '/courts/id/{courtId}': {
    /**
     * Get specified court
     * @description Information on a specific court
     */
    get: operations['getCourtFromId']
  }
  '/courts/id/{courtId}/buildings/main': {
    /**
     * Get the main building by court ID
     * @description Information on the main building by court ID
     */
    get: operations['findMainBuilding']
  }
  '/courts/id/{courtId}/buildings/id/{buildingId}': {
    /**
     * Get specified building
     * @description Information on a specific building
     */
    get: operations['getBuildingFromId']
  }
  '/courts/id/{courtId}/buildings/id/{buildingId}/contacts/id/{contactId}': {
    /**
     * Get specified contact
     * @description Information on a specific contact
     */
    get: operations['getContactFromId']
  }
  '/courts/buildings/sub-code/{subCode}': {
    /**
     * Get specified building by sub-code
     * @description Information on a specific building by sub-code
     */
    get: operations['getBuildingFromSubCode']
  }
  '/courts/all': {
    /**
     * Get all active and inactive courts
     * @description All active/inactive courts
     */
    get: operations['getAllCourts']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    DlqMessage: {
      body: {
        [key: string]: Record<string, never>
      }
      messageId: string
    }
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    /** @description Court Update Record */
    UpdateCourtDto: {
      /**
       * @description Name of the court
       * @example Accrington Youth Court
       */
      courtName: string
      /**
       * @description Description of the court
       * @example Accrington Youth Court
       */
      courtDescription?: string
      /**
       * @description Type of court
       * @example COU
       */
      courtType: string
      /** @description Whether the court is still active */
      active: boolean
    }
    /** @description Building */
    BuildingDto: {
      /**
       * Format: int64
       * @description Unique ID of the building
       * @example 10000
       */
      id: number
      /**
       * @description Court Id for this building
       * @example ACCRYC
       */
      courtId: string
      /**
       * @description Sub location code for referencing building
       * @example AAABBB
       */
      subCode?: string
      /**
       * @description Building Name
       * @example Crown House
       */
      buildingName?: string
      /**
       * @description Street Number and Name
       * @example 452 West Street
       */
      street?: string
      /**
       * @description Locality
       * @example West Cross
       */
      locality?: string
      /**
       * @description Town/City
       * @example Swansea
       */
      town?: string
      /**
       * @description County
       * @example South Glamorgan
       */
      county?: string
      /**
       * @description Postcode
       * @example SA3 4HT
       */
      postcode?: string
      /**
       * @description Country
       * @example UK
       */
      country?: string
      /** @description List of contacts for this building by type */
      contacts?: components['schemas']['ContactDto'][]
      /** @description Whether the building is active */
      active: boolean
    }
    /** @description Contact */
    ContactDto: {
      /**
       * Format: int64
       * @description Unique ID of the contact
       * @example 10000
       */
      id: number
      /**
       * @description Court Id for this contact
       * @example ACCRYC
       */
      courtId: string
      /**
       * Format: int64
       * @description Building Id for this contact
       * @example 12312
       */
      buildingId: number
      /**
       * @description Type of contact
       * @example TEL
       * @enum {string}
       */
      type: 'TEL' | 'FAX'
      /**
       * @description Details of the contact
       * @example 555 55555
       */
      detail: string
    }
    /** @description Court Information */
    CourtDto: {
      /**
       * @description Court ID
       * @example ACCRYC
       */
      courtId: string
      /**
       * @description Name of the court
       * @example Accrington Youth Court
       */
      courtName: string
      /**
       * @description Description of the court
       * @example Accrington Youth Court
       */
      courtDescription?: string
      type: components['schemas']['CourtTypeDto']
      /** @description Whether the court is still active */
      active: boolean
      /** @description List of buildings for this court entity */
      buildings: components['schemas']['BuildingDto'][]
    }
    /** @description Court Type */
    CourtTypeDto: {
      /**
       * @description Type of court
       * @example COU
       */
      courtType: string
      /**
       * @description Description of the type of court
       * @example County Court/County Divorce Ct
       */
      courtName: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
      errors?: string[]
    }
    /** @description Building Update Record */
    UpdateBuildingDto: {
      /**
       * @description Building Name
       * @example Crown House
       */
      buildingName?: string
      /**
       * @description Street Number and Name
       * @example 452 West Street
       */
      street?: string
      /**
       * @description Locality
       * @example West Cross
       */
      locality?: string
      /**
       * @description Town/City
       * @example Swansea
       */
      town?: string
      /**
       * @description County
       * @example South Glamorgan
       */
      county?: string
      /**
       * @description Postcode
       * @example SA3 4HT
       */
      postcode?: string
      /**
       * @description Country
       * @example UK
       */
      country?: string
      /**
       * @description Sub location code for referencing building
       * @example AAABBB
       */
      subCode?: string
      /**
       * @description Whether the building is active
       * @default true
       * @example true
       */
      active: boolean
      /** @description List of contacts for this building by type, can only be used on a new court */
      contacts: components['schemas']['UpdateContactDto'][]
    }
    /** @description Contact */
    UpdateContactDto: {
      /**
       * @description Type of contact
       * @example TEL
       * @enum {string}
       */
      type: 'TEL' | 'FAX'
      /**
       * @description Details of the contact
       * @example 555 55555
       */
      detail: string
    }
    /** @description Court Insert Record */
    InsertCourtDto: {
      /**
       * @description Court ID
       * @example ACCRYC
       */
      courtId: string
      /**
       * @description Name of the court
       * @example Accrington Youth Court
       */
      courtName: string
      /**
       * @description Description of the court
       * @example Accrington Youth Court
       */
      courtDescription?: string
      /**
       * @description Type of court
       * @example COU
       */
      courtType: string
      /** @description Whether the court is still active */
      active: boolean
      /** @description List of buildings for this court */
      buildings: components['schemas']['UpdateBuildingDto'][]
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    CourtDtoPage: {
      content?: components['schemas']['CourtDto'][]
      pageable?: components['schemas']['PageableObject']
      last?: boolean
      /** Format: int32 */
      totalPages?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      size?: number
      /** Format: int32 */
      number?: number
      sort?: components['schemas']['SortObject']
      first?: boolean
      /** Format: int32 */
      numberOfElements?: number
      empty?: boolean
    }
    PageableObject: {
      /** Format: int64 */
      offset?: number
      sort?: components['schemas']['SortObject']
      /** Format: int32 */
      pageSize?: number
      paged?: boolean
      unpaged?: boolean
      /** Format: int32 */
      pageNumber?: number
    }
    SortObject: {
      empty?: boolean
      sorted?: boolean
      unsorted?: boolean
    }
    Pageable: {
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      sort?: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  retryDlq: {
    parameters: {
      path: {
        dlqName: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      path: {
        queueName: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  /**
   * Update specified court details
   * @description Updates court information, role required is MAINTAIN_REF_DATA
   */
  updateCourt: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCourtDto']
      }
    }
    responses: {
      /** @description Court Information Updated */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto']
        }
      }
      /** @description Information request to update court */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to make court update */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Court ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Update specified building details
   * @description Updates building information, role required is MAINTAIN_REF_DATA
   */
  updateBuilding: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
        /**
         * @description Building ID
         * @example 234231
         */
        buildingId: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBuildingDto']
      }
    }
    responses: {
      /** @description Building Information Updated */
      200: {
        content: {
          'application/json': components['schemas']['BuildingDto']
        }
      }
      /** @description Information request to update building */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to make building update */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Building ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Delete specified building
   * @description Deletes building information, role required is MAINTAIN_REF_DATA
   */
  deleteBuilding: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
        /**
         * @description Building ID
         * @example 234231
         */
        buildingId: string
      }
    }
    responses: {
      /** @description Building Information Deleted */
      200: {
        content: {
          'application/json': components['schemas']['BuildingDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to delete building */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Building ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Update specified building contact details
   * @description Updates contact information, role required is MAINTAIN_REF_DATA
   */
  updateContact: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
        /**
         * @description Building ID
         * @example 234231
         */
        buildingId: string
        /**
         * @description Contact ID
         * @example 11111
         */
        contactId: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateContactDto']
      }
    }
    responses: {
      /** @description Building Contact Information Updated */
      200: {
        content: {
          'application/json': components['schemas']['ContactDto']
        }
      }
      /** @description Information request to update contact */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to make contact update */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Contact ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Delete specified building contact details
   * @description Deletes contact information, role required is MAINTAIN_REF_DATA
   */
  deleteContact: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
        /**
         * @description Building ID
         * @example 234231
         */
        buildingId: string
        /**
         * @description Contact ID
         * @example 11111
         */
        contactId: string
      }
    }
    responses: {
      /** @description Building Contact Information Deleted */
      200: {
        content: {
          'application/json': components['schemas']['ContactDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to delete contact */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Contact ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Add a new court
   * @description Adds a new court information, role required is MAINTAIN_REF_DATA
   */
  insertCourt: {
    requestBody: {
      content: {
        'application/json': components['schemas']['InsertCourtDto']
      }
    }
    responses: {
      /** @description Court Information Inserted */
      201: {
        content: {
          'application/json': components['schemas']['CourtDto']
        }
      }
      /** @description Information request to add a court */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to make court insert */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Add a new building to a court
   * @description Adds a new building to court, role required is MAINTAIN_REF_DATA
   */
  insertBuilding: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBuildingDto']
      }
    }
    responses: {
      /** @description Building Information Inserted */
      201: {
        content: {
          'application/json': components['schemas']['BuildingDto']
        }
      }
      /** @description Invalid request to add a building */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to make building insert */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Add a new contact to a building
   * @description Adds a new contact to building, role required is MAINTAIN_REF_DATA
   */
  insertContact: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
        /**
         * @description Contact ID
         * @example 11111
         */
        buildingId: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateContactDto']
      }
    }
    responses: {
      /** @description Contact Information Inserted */
      201: {
        content: {
          'application/json': components['schemas']['ContactDto']
        }
      }
      /** @description Invalid request to add a contact */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to add contact insert */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      path: {
        dlqName: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
  /**
   * Get all active courts
   * @description All courts (active only)
   */
  getActiveCourts: {
    responses: {
      /** @description All Active Court Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto'][]
        }
      }
    }
  }
  /**
   * Get all types of court
   * @description All court types
   */
  getCourtTypes: {
    responses: {
      /** @description All Types of courts returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtTypeDto'][]
        }
      }
    }
  }
  /**
   * Get page of courts
   * @description Page of courts
   */
  getPageOfCourts: {
    parameters: {
      query?: {
        /**
         * @description Active?
         * @example true
         */
        active?: boolean
        /**
         * @description Court Type
         * @example CRN
         */
        courtTypeIds?: string[]
        /**
         * @description Text search
         * @example Sheffield
         */
        textSearch?: string
        pageable?: components['schemas']['Pageable']
      }
    }
    responses: {
      /** @description All Court Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtDtoPage'][]
        }
      }
    }
  }
  /**
   * Get specified court
   * @description Information on a specific court
   */
  getCourtFromId: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
      }
    }
    responses: {
      /** @description Court Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto']
        }
      }
      /** @description Incorrect request to get court information */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Court ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Get the main building by court ID
   * @description Information on the main building by court ID
   */
  findMainBuilding: {
    parameters: {
      path: {
        /**
         * @description Court Id
         * @example BRMNCC
         */
        courtId: string
      }
    }
    responses: {
      /** @description Building Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['BuildingDto']
        }
      }
      /** @description Incorrect request to get building information */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Building SubCode not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Get specified building
   * @description Information on a specific building
   */
  getBuildingFromId: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example BRMNCC
         */
        courtId: string
        /**
         * @description Building ID
         * @example 234231
         */
        buildingId: string
      }
    }
    responses: {
      /** @description Building Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['BuildingDto']
        }
      }
      /** @description Incorrect request to get building information */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Building ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Get specified contact
   * @description Information on a specific contact
   */
  getContactFromId: {
    parameters: {
      path: {
        /**
         * @description Court ID
         * @example ACCRYC
         */
        courtId: string
        /**
         * @description Building ID
         * @example 234231
         */
        buildingId: string
        /**
         * @description Contact ID
         * @example 11111
         */
        contactId: string
      }
    }
    responses: {
      /** @description Contact Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['ContactDto']
        }
      }
      /** @description Incorrect request to get contact information */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Contact ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Get specified building by sub-code
   * @description Information on a specific building by sub-code
   */
  getBuildingFromSubCode: {
    parameters: {
      path: {
        /**
         * @description Building Sub Code
         * @example BCCACC
         */
        subCode: string
      }
    }
    responses: {
      /** @description Building Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['BuildingDto']
        }
      }
      /** @description Incorrect request to get building information */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Building SubCode not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Get all active and inactive courts
   * @description All active/inactive courts
   */
  getAllCourts: {
    responses: {
      /** @description All Court Information Returned (Active only) */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto'][]
        }
      }
    }
  }
}
