---
# Per environment values which override defaults in hmpps-remand-and-sentencing/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: remand-and-sentencing-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://remand-and-sentencing-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    COURT_REGISTER_API_URL: "https://court-register-api-preprod.hmpps.service.justice.gov.uk"
    MANAGE_OFFENCES_API_URL: "https://manage-offences-api-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    DIGITAL_PRISON_SERVICES_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    COMMON_COMPONENTS_ENABLED: 'true'
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api-preprod.hmpps.service.justice.gov.uk"
    DOCUMENT_MANAGEMENT_API_URL: "https://document-api-preprod.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    ADJUSTMENTS_UI_URL: "https://adjust-release-dates-preprod.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"
    COURT_CASES_RELEASE_DATES_API_URL: "https://court-cases-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    FEATURES_VIEW_ONLY_ENABLED: 'true'

  allowlist:
    penetration-test-ip-1: 54.37.241.156/30
    penetration-test-ip-2: 167.71.136.237/32
    groups:
      - internal
      - prisons
      - circleci

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: legacy-replacement-alerts-non-prod
