---
# Per environment values which override defaults in hmpps-remand-and-sentencing/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: remand-and-sentencing-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://remand-and-sentencing-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    COURT_REGISTER_API_URL: "https://court-register-dev.hmpps.service.justice.gov.uk"
    MANAGE_OFFENCES_API_URL: "https://manage-offences-api-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
