---
# Per environment values which override defaults in hmpps-remand-and-sentencing/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: remand-and-sentencing-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://remand-and-sentencing-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    COURT_REGISTER_API_URL: "https://court-register-dev.hmpps.service.justice.gov.uk"
    MANAGE_OFFENCES_API_URL: "https://manage-offences-api-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    DIGITAL_PRISON_SERVICES_URL: "https://digital-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    COMMON_COMPONENTS_ENABLED: 'true'
    CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-dev.hmpps.service.justice.gov.uk"
    ADJUSTMENTS_UI_URL: "https://adjust-release-dates-dev.hmpps.service.justice.gov.uk"
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api-dev.hmpps.service.justice.gov.uk"
    DOCUMENT_MANAGEMENT_API_URL: "https://document-api-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev